name: Pylint Syntax Checking

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint 
        pip install cython
        pip install -r requirements.txt
        pylint ogm
